version: '3.8'

services:
  presentation:
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    image: vietafood/presentation:latest
    ports:
      - "8080:8080"
    depends_on:
      - vietfood_database
    networks:
      - vietafood-network
      
  vietfood_database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassw0rd!  # Replace with actual environment variable name
    ports:
      - "1431:1431"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - vietafood-network

volumes:
  sqlserver-data:

networks:
  vietafood-network:
    driver: bridge
