version: '3.4'

services:
  presentation:
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    image: vietafood/presentation:latest
    ports:
      - "8080:8080"
    depends_on:
      - vietfood_database
    networks:
      - vietafood-network

  vietfood_database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=12345
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - vietafood-network

volumes:
  sql-data:

networks:
  vietafood-network:
    driver: bridge
